name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install SonarScanner
      run: |
        curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli.zip

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: sqp_6b62672b7aad2b6096527adac230415c496c4444
      run: |
        ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
          -Dsonar.projectKey=test \
          -Dsonar.organization=test \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://sonarqubebhaifi.htcpoc.com \
          -Dsonar.login= sqp_6b62672b7aad2b6096527adac230415c496c4444
